export class Travel {
    TraveId: string;
    codeTravel: string;
    TypeTravel : string;
    Source: string;
    DepartamentSource: string;
    DirectionSource: string;
    LatitudeSource: number;
    LongitudeSource: number;
    Destiny: string;
    DepartamentDestiny: string;
    DirectionDestiny: string;
    LatitudeDestiny: number;
    LongitudeDestiny: number;
    ProductName: string;
    Amount: number;
    DateTravel: string;
    TimerStar: string;
    ClientName: string;
    DowloadStar: string;
    DowloadEnd: string;
    TimerEndTravel: string;
    DateTravelEnd: string;
    TripStarTime: string;
    StatusTravel: number;
    StatusTravelAvailability: number;
    ConsignmentDocument: string;
    ManifestDocument: string;
    Country: string;
    LissenteVehicle: string;
    UserId: number;
    CompanyId: number;
    CompanyName: string;
    UserName : string;
    UserLastName : string;
    VehicleId: number;
    LicenseVehiculo : string;
    Model : string;

    observationsOfTravel : string;
    LoadEnd : string;
    LoadStar : string;
}
