export class Vehicle{
    VehicleId : number;
    LicenseVehiculo : string;
    Model : string;
    TypeTrailer : string;
    Soat : string;
    StatusVehicle : number;
    StatusTravel : number;
    SoatDocument : string;
    TechnomechanicsDocument : string;
    PolicyDocument : string;
    CardPropertyDocument : string
    UserId : number;
    CompanyId : number;
    CompanyName : string;
    FirstName : string;
    LastName : string;
    Status : string;
    userName : string;
}